#pragma once
#include "disassemblyStructs.h"

// Intel 64 and IA-32 Architectures Software Developer’s Manuals:
//	intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html

// Appendix A: A.4.2 table A-6

// any NO_OPERAND_CODE means that the operand code will be what is in the regular opcode map

// this is only up to group 6. These groups only depend on ModR/M bits 3-5
const struct Opcode extendedOpcodeMapThroughGroupSix[7][8] = // [group index][ModR/M bits 3-5]
{
	{	// group 1
		{ ADD, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ OR, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ ADC, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ SBB, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ AND, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ SUB, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ XOR, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ CMP, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }
	},
	{	// group 1A
		{ POP, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC }
	},
	{	// group 2
		{ ROL, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ ROR, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ RCL, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ RCR, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ SHL, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ SHR, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ NO_MNEMONIC },
		{ SAR, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }
	},
	{	// group 3
		{ TEST, -1, NO_OPERAND_CODE, Ib, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }, // second operands is Iz if opcode is 0xF7
		{ NO_MNEMONIC },
		{ NOT, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ NEG, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ MUL, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ IMUL, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT},
		{ DIV, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ IDIV, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }
	},
	{	// group 4
		{ INC, -1, Eb, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ DEC, -1, Eb, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC }
	},
	{	// group 5
		{ INC, -1, Ev, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ DEC, -1, Ev, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ CALL_NEAR, -1, Ev, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, f64 },
		{ CALL_FAR, -1, Ep, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ JMP_NEAR, -1, Ev, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, f64 },
		{ JMP_FAR, -1, Mp, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, d64 },
		{ PUSH, -1, Ev, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ NO_MNEMONIC }
	},
	{	// group 6
		{ SLDT, -1, Ew, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }, // first operand is Rv/Mw, leaving Ew
		{ STR, -1, Ew, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }, // first operand is Rv/Mw, leaving Ew
		{ LLDT, -1, Ew, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ LTR, -1, Ew, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ VERR, -1, Ew, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ VERW, -1, Ew, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ NO_MNEMONIC }
	}
};

// group 7 where Mod 7,6 is not 11B
const struct Opcode extendedOpcodeMapGroup7[8] = // [ModR/M bits 3-5]
{
	{ SGDT, -1, Mv, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }, // first operand is Ms, leaving Mv
	{ SIDT, -1, Mv, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }, // first operand is Ms, leaving Mv
	{ LGDT, -1, Mv, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }, // first operand is Ms, leaving Mv
	{ LIDT, -1, Mv, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }, // first operand is Ms, leaving Mv
	{ SMSW, -1, Ew, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }, // first operand is Mw/Rv, leaving Ew
	{ NO_MNEMONIC },
	{ LMSW, -1, Ew, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ INVLPG, -1, Mb, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }
};

// group 7 where Mod 7,6 is 11B
const struct Opcode extendedOpcodeMapGroup711B[8][8] =  // [ModR/M bits 3-5][ModR/M bits 0-2]
{
	{
		{ NO_MNEMONIC },
		{ VMCALL, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ VMLAUNCH, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ VMRESUME, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ VMXOFF, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC }
	},
	{
		{ MONITOR, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ MWAIT, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ CLAC, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ STAC, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ ENCLS, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }
	},
	{
		{ XGETBV, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ XSETBV, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ VMFUNC, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ XEND, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ XTEST, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ ENCLU, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }
	},
	{
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC }
	},
	{
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC }
	},
	{
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC }
	},
	{
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC }
	},
	{
		{ SWAPGS, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, o64 },
		{ RDTSCP , -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
		{ NO_MNEMONIC },
	}
};

// group 8
const struct Opcode extendedOpcodeMapGroup8[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ BT, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ BTS, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ BTR, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ BTC, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }
};

// group 9 with no prefix and Mod 7,6 is not 11B
const struct Opcode extendedOpcodeMapGroup9[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ CMPXCH8B, -1, Mq, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }, // CMPXCHG16B and Mdq if REX.w
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ VMPTRLD, -1, Mq, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ VMPTRST, -1, Mq, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }
};
const struct Opcode alternateCMPXCH = { CMPXCHG16B, -1, Mdq, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT };

// group 9 with 0x66 prefix and Mod 7,6 is not 11B
const struct Opcode extendedOpcodeMapGroup966[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ VMCLEAR, -1, Mq, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC }
};

// group 9 with 0xF3 prefix and Mod 7,6 is not 11B
const struct Opcode extendedOpcodeMapGroup9F3[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ VMXON, -1, Mq, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC }
};

// group 9 with no prefix and Mod 7,6 is 11B
const struct Opcode extendedOpcodeMapGroup911B[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ RDRAND, -1, Rv, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ RDSEED, -1, Rv, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }
};

// group 9 with 0xF3 prefix and Mod 7,6 is 11B
const struct Opcode extendedOpcodeMapGroup9F311B[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ RDPID, -1, Rd, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }, // first operand is Rd/q
};

// group 10 is UD1

// group 11 for opcode 0xC6
const struct Opcode extendedOpcodeMapGroup11C6[8] = // [ModR/M bits 3-5]
{
	{ MOV, -1, Eb, Ib, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ XABORT, -1, Ib, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }
};

// group 11 for opcode 0xC7
const struct Opcode extendedOpcodeMapGroup11C7[8] = // [ModR/M bits 3-5]
{
	{ MOV, -1, Ev, Iz, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ XBEGIN, -1, Jz, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT }
};

// group 12 with no prefix and Mod 7,6 is 11B
const struct Opcode extendedOpcodeMapGroup1211B[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ PSRLW, -1, Nq, Ib, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ PSRAW, -1, Nq, Ib, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ PSLLW, -1, Nq, Ib, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
};

// group 12 with 0x66 prefix and Mod 7,6 is 11B
const struct Opcode extendedOpcodeMapGroup126611B[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ VPSRLW, -1, Hx, Ux, Ib, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ VPSRAW, -1, Hx, Ux, Ib, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ VPSLLW, -1, Hx, Ux, Ib, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
};

// group 13 with no prefix and Mod 7,6 is 11B
const struct Opcode extendedOpcodeMapGroup1311B[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ PSRLD, -1, Nq, Ib, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ PSRAD, -1, Nq, Ib, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ PSLLD, -1, Nq, Ib, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
};

// group 13 with 0x66 prefix and Mod 7,6 is 11B
const struct Opcode extendedOpcodeMapGroup136611B[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ VPSRLD, -1, Hx, Ux, Ib, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ VPSRAD, -1, Hx, Ux, Ib, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ VPSLLD, -1, Hx, Ux, Ib, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
};

// group 14 with no prefix and Mod 7,6 is 11B
const struct Opcode extendedOpcodeMapGroup1411B[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ PSRLQ, -1, Nq, Ib, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ PSLLQ, -1, Nq, Ib, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
};

// group 14 with 0x66 prefix and Mod 7,6 is 11B
const struct Opcode extendedOpcodeMapGroup146611B[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ VPSRLQ, -1, Hx, Ux, Ib, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ VPSRLDQ, -1, Hx, Ux, Ib, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ VPSLLQ, -1, Hx, Ux, Ib, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ VPSLLDQ, -1, Hx, Ux, Ib, NO_OPERAND_CODE, NO_SUPERSCRIPT },
};

// group 15 with no prefix and Mod 7,6 is not 11B
const struct Opcode extendedOpcodeMapGroup15[8] = // [ModR/M bits 3-5]
{
	{ FXSAVE, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ FXRSTOR, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ LDMXCSR, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ STMXCSR, -1, Md, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ XSAVE, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ XRSTOR, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ XSAVEOPT, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ CLFLUSH, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
};

// group 15 with no prefix and Mod 7,6 is 11B
const struct Opcode extendedOpcodeMapGroup1511B[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ LFENCE, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ MFENCE, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ SFENCE, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
};

// group 15 with 0xF3 prefix and Mod 7,6 is 11B
const struct Opcode extendedOpcodeMapGroup15F311B[8] = // [ModR/M bits 3-5]
{
	{ RDFSBASE, -1, Ry, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ RDGSBASE, -1, Ry, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ WRFSBASE, -1, Ry, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ WRGSBASE, -1, Ry, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC }
};

// group 16
const struct Opcode extendedOpcodeMapGroup16[8] = // [ModR/M bits 3-5]
{
	{ PREFETCHNTA, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ PREFETCHT0, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ PREFETCHT1, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ PREFETCHT2, -1, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC }
};

// group 17
const struct Opcode extendedOpcodeMapGroup17[8] = // [ModR/M bits 3-5]
{
	{ NO_MNEMONIC },
	{ BLSR, -1, By, Ey, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ BLSMSK, -1, By, Ey, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ BLSI, -1, By, Ey, NO_OPERAND_CODE, NO_OPERAND_CODE, NO_SUPERSCRIPT },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
	{ NO_MNEMONIC },
};