#pragma once

// Intel 64 and IA-32 Architectures Software Developer’s Manuals:
//	intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html

// underscore prefixes are to avoid name conflicts

enum Mnemonic
{
	NO_MNEMONIC,

	MOV, VMOVUPS, MOVUPS, VMOVUPD, MOVUPD, VMOVSS, MOVSS, VMOVSD, MOVSD, MOVSX, VMOVD, MOVD, VMOVAPS, MOVAPS, VMOVAPD, MOVAPD, VMOVLPS, MOVLPS, VMOVHLPS, MOVHLPS, VMOVLPD, MOVLPD, VMOVSLDUP, MOVSLDUP, VMOVDDUP, MOVDDUP, VMOVHPS, MOVHPS, VMOVLHPS, MOVLHPS, VMOVHPD, MOVHPD, VMOVSHDUP, MOVSHDUP, VMOVNTPS, MOVNTPS, VMOVNTPD, MOVNTPD, VMOVMSKPS, MOVMSKPS, VMOVMSKPD, MOVMSKPD, MOVS, MOVSXD, MOVZX, VMOVQ, MOVQ, VMOVDQA, MOVDQA, VMOVDQU, MOVDQU, MOVNTI, MOVQ2DQ, MOVDQ2Q, VPMOVMSKB, PMOVMSKB, MOVNTQ, MOVNTDQ, MASKMOVQ, MASKMOVDQU,
	LEA,
	ADD, VADDPS, ADDPS, VADDPD, ADDPD, VADDSS, ADDSS, VADDSD, ADDSD, VHADDPD, HADDPD, VHADDPS, HADDPS, XADD, VPADDQ, PADDQ,
	SUB, VSUBPS, SUBPS, VSUBPD, SUBPD, VSUBSS, SUBSS, VSUBSD, SUBSD, VHSUBPD, HSUBPD, VHSUBPS, HSUBPS,
	AND, VANDPS, ANDPS, VANDPD, ANDPD, VANDNPS, ANDNPS, VANDNPD, ANDNPD, VPAND, PAND, VPANDN, PANDN,
	OR, VORPS, ORPS, VORPD, ORPD,
	XOR, VXORPD, XORPD, VXORPS, XORPS, VPXOR, PXOR,
	SHL, SHLD, 
	SHR, SHRD,
	IMUL, VMULPS, MULPS, VMULPD, MULPD, VMULSS, MULSS, VMULSD, MULSD,
	IDIV, VDIVPS, DIVPS, VDIVPD, DIVPD, VDIVSS, DIVSS, VDIVSD, DIVSD,
	VCVTPS2PD, CVTPS2PD, VCVTSS2SD, CVTSS2SD, CVTPI2PD, VCVTSI2SD, CVTSI2SD, VCVTDQ2PD, CVTDQ2PD,
	VCVTPD2PS, CVTPD2PS, VCVTSD2SS, CVTSD2SS, CVTPI2PS, VCVTSI2SS, CVTSI2SS, VCVTDQ2PS, CVTDQ2PS,

	CVTTPS2PI, CVTTPD2PI, VCVTTSS2SI, CVTTSS2SI, VCVTTSD2SI, CVTTSD2SI, CVTPS2PI, CVTPD2PI, VCVTSS2SI, CVTSS2SI, VCVTSD2SI, CVTSD2SI, VCVTPS2DQ, CVTPS2DQ, VCVTTPS2DQ, CVTTPS2DQ, VCVTTPD2DQ, CVTTPD2DQ, VCVTPD2DQ, CVTPD2DQ,
	CMP, VCOMISS, COMISS, VCOMISD, COMISD,

	VPMULLW, PMULLW,

	JA_SHORT, JB_SHORT, JBE_SHORT, JG_SHORT, JL_SHORT, JLE_SHORT, JNB_SHORT, JGE_SHORT, JNO_SHORT, JNP_SHORT, JNS_SHORT, JNZ_SHORT, JO_SHORT, JP_SHORT, JS_SHORT, JZ_SHORT, JMP_SHORT, JMP_FAR, JMP_NEAR,

	CMOVO, CMOVNO, CMOVB, CMOVNB, CMOVZ, CMOVNZ, CMOVBE, CMOVA, CMOVS, CMOVNS, CMOVP, CMOVNP, CMOVL, CMOVGE, CMOVLE, CMOVG,

	AAA, AAD, AAM, AAS, ADC, ARPL,
	BOUND, BSF, BSR, BSWAP, BT, BTC, BTR, BTS, BNDLDX, BNDMOV, BNDCL, BNDCU, BNDSTX, BNDMK, BNDCN,
	CALL_FAR, CALL_NEAR, CDQ, CWD, CQO, CLAC, CLC, CLD, CLI, CLTS, CMC, CMPS, CMPXCHG, CPUID, CBW, CWDE, CDQE,
	DAA, DAS, DEC, DIV,
	EMMS, ENCLS, ENCLU, ENDBR, ENTER,
	F2XM1, FABS, FADD, FADDP, FBLD, FBSTP, FCHS, FCLEX, FCMOVB, FCMOVBE, FCMOVE, FCMOVNB, FCMOVNBE, FCMOVNE, FCMOVNU, FCMOVU, FCOM, FCOMI, FCOMIP, FCOMP, FCOMPP, FCOS, FDECSTP, FDIV, FDIVP, FDIVR, FDIVRP, FFREE, FIADD, FICOM, FICOMP, FIDIV, FIDIVR, FILD, FIMUL, FINCSTP, FINIT, FIST, FISTP, FISTTP, FISUB, FISUBR, FLD, FLD1, FLDCW, FLDENV, FLDL2E, FLDL2T, FLDLG2, FLDLN2, FLDPI, FLDZ, FMUL, FMULP, FNOP, FPATAN, FPREM, FPREM1, FPTAN, FRNDINT, FRSTOR, FSAVE, FSCALE, FSIN, FSINCOS, FSQRT, FST, FSTCW, FSTENV, FSTP, FSTSW, FSUB, FSUBP, FSUBR, FSUBRP, FTST, FUCOM, FUCOMI, FUCOMIP, FUCOMP, FUCOMPP, FXAM, FXCH, FXTRACT, FYL2X, FYL2XP1,
	GETSEC,
	HLT,
	_IN, INC, INS, _INT, INT1, INT3, INTO, INVD, IRET,
	JRCXZ, JMPE,
	LAHF, LAR, VLDDQU, LDDQU, LDS, LEAVE, LES, LFS, LGS, LODS, LOOP, LOOPNZ, LOOPZ, LSL, LSS, LZCNT,
	MONITOR, MUL, MWAIT,
	NEG, NOP, NOT,
	_OUT, OUTS,
	POP, POPAD, POP_DS, POP_ES, POP_FS, POP_GS, POP_SS, POPF, PREFETCHW, PUSH, PUSHAD, PUSH_CS, PUSH_DS, PUSH_ES, PUSH_FS, PUSH_GS, PUSH_SS, PUSHF, POPCNT, VPINSRW, PINSRW, VPEXTRW, PEXTRW,
	RCL, RCR, RDMSR, RDPMC, RDTSC, RET_FAR, RET_NEAR, ROL, ROR, RSM, VRCPPS, RCPPS, VRCPSS, RCPSS,
	SAHF, SAR, SBB, SCAS, SETA, SETB, SETBE, SETG, SETL, SETLE, SETNB, SETNL, SETNO, SETNP, SETNS, SETNZ, SETO, SETP, SETS, SETZ, STAC, STC, STD, STI, STOS, SYSCALL, SYSENTER, SYSEXIT, SYSRET,
	TEST, TZCNT,
	VUCOMISD, UCOMISD, VUCOMISS, UCOMISS, VUNPCKHPD, UNPCKHPD, VUNPCKHPS, UNPCKHPS, VUNPCKLPD, UNPCKLPD, VUNPCKLPS, UNPCKLPS,
	VMCALL, VMFUNC, VMLAUNCH, VMRESUME, VMXOFF, VMREAD, VMWRITE,
	WAIT, WBINVD, WRMSR,
	XABORT, XBEGIN, XCHG, XEND, XGETBV, XLAT, XSETBV, XTEST,

	VSQRTPS, SQRTPS, VSQRTPD, SQRTPD, VSQRTSS, SQRTSS, VSQRTSD, SQRTSD, VRSQRTPS, RSQRTPS, VRSQRTSS, RSQRTSS,

	VMINPS, MINPS, VMINPD, MINPD, VMINSS, MINSS, VMINSD, MINSD,
	VMAXPS, MAXPS, VMAXPD, MAXPD, VMAXSS, MAXSS, VMAXSD, MAXSD,

	VADDSUBPD, ADDSUBPD, VADDSUBPS, ADDSUBPS,

	VPUNPCKLBW, PUNPCKLBW, VPUNPCKLWD, PUNPCKLWD, VPUNPCKLDQ, PUNPCKLDQ, VPACKSSWB, PACKSSWB, VPACKUSWB, PACKUSWB, VPUNPCKHBW, PUNPCKHBW, VPUNPCKHWD, PUNPCKHWD, VPUNPCKHDQ, PUNPCKHDQ, VPACKSSDW, PACKSSDW, VPUNPCKLQDQ, PUNPCKLQDQ, VPUNPCKHQDQ, PUNPCKHQDQ,
	VPCMPGTB, PCMPGTB, VPCMPGTW, PCMPGTW, VPCMPGTD, PCMPGTD,

	PSHUFW, VPSHUFD, PSHUFD, VPSHUFHW, PSHUFHW, VPSHUFLW, PSHUFLW,

	VPCMPEQB, PCMPEQB, VPCMPEQW, PCMPEQW, VPCMPEQD, PCMPEQD,

	VCMPPS, CMPPS, VCMPPD, CMPPD, VCMPSS, CMPSS, VCMPSD, CMPSD,

	VSHUFPS, SHUFPS, VSHUFPD, SHUFPD,

	VPSRLW, PSRLW, VPSRLD, PSRLD, VPSRLQ, PSRLQ, VPSRLDQ, PSRLDQ, VPSLLDQ, PSLLDQ,

	VPSUBUSB, PSUBUSB, VPSUBUSW, PSUBUSW,
	VPMINUB, PMINUB,
	VPADDUSB, PADDUSB, VPADDUSW, PADDUSW,
	PMAXUB,
	VPAVGB, PAVGB, VPSRAW, PSRAW, VPSRAD, PSRAD, VPAVGW, PAVGW, VPMULHUW, PMULHUW, VPMULHW, PMULHW,
	VPSUBSB, PSUBSB, VPSUBSW, PSUBSW, VPMINSW, PMINSW, VPOR, POR, VPADDSB, PADDSB, VPADDSW, PADDSW, VPMAXSW, PMAXSW,
	VPSLLW, PSLLW, PSLLD, PSLLQ, PMULUDQ, PMADDWD, PSADBW,
	PSUBB, PSUBW, PSUBD, PSUBQ, PADDB, PADDW, PADDD,

	FXSAVE, FXRSTOR, LDMXCSR, STMXCSR, XSAVE, XRSTOR, XSAVEOPT, CLFLUSH,
	LFENCE, MFENCE, SFENCE,
	RDFSBASE, RDGSBASE, WRFSBASE, WRGSBASE,
	RDRAND, RDSEED, RDPID,

	PSHUFB, 
	PHADDW, PHADDD, PHADDSW, 
	PMADDUBSW, 
	PHSUBW, PHSUBD, PHSUBSW, 
	PSIGNB, PSIGNW, PSIGND,
	PMULHRSW,
	PERMILPS, PERMILPD,
	TESTPS, TESTPD,
	PBLENDVB,
	CVTPH2PS,
	BLENDVPS, BLENDVPD,
	PERMPS,
	PTEST,
	BROADCASTSS, BROADCASTSD, BROADCASTF128,
	PABSB, PABSW, PABSD,
	PMOVSXBW, PMOVSXBD, PMOVSXBQ, PMOVSXWD, PMOVSXWQ, PMOVSXDQ,
	PMULDQ,
	PCMPEQQ,
	MOVNTDQA,
	PACKUSDW,
	MASKMOVPS, MASKMOVPD, 
	PMOVZXBW, PMOVZXBD, PMOVZXBQ, PMOVZXWD, PMOVZXWQ, PMOVZXDQ, 
	PERMD, 
	PCMPGTQ,
	PMINSB, PMINSD, PMINUW, PMINUD,
	PMAXSB, PMAXSD, PMAXUW, PMAXUD,
	PMULLD, 
	PHMINPOSUW, 
	PSRLVD, PSRAVD, PSLLVD,
	PBROADCASTD, PBROADCASTQ, BROADCASTI128, PBROADCASTB, PBROADCASTW,
	INVEPT, INVVPID, INVPCID, 
	PMASKMOVD, 
	GATHERDD, GATHERQD, GATHERDPS, GATHERQPS,
	FMADDSUB132PS, FMSUBADD132PS, FMADD132PS, FMADD132SS, FMSUB132PS, FMSUB132SS, FNMADD132PS, FNMADD132SS, FNMSUB132PS, FNMSUB132SS,
	FMADDSUB213PS, FMSUBADD213PS, FMADD213PS, FMADD213SS, FMSUB213PS, FMSUB213SS, FNMADD213PS, FNMADD213SS, FNMSUB213PS, FNMSUB213SS,
	FMADDSUB231PS, FMSUBADD231PS, FMADD231PS, FMADD231SS, FMSUB231PS, FMSUB231SS, FNMADD231PS, FNMADD231SS, FNMSUB231PS, FNMSUB231SS,
	SHA1NEXTE, SHA1MSG1, SHA1MSG2, 
	SHA256RNDS2, SHA256MSG1, SHA256MSG2,
	AESIMC, AESENC, AESENCLAST, AESDEC, AESDECLAST,
	MOVBE, 
	CRC32,
	ANDN,
	BZHI,
	PEXT, PDEP,
	ADCX, ADOX, 
	MULX, 
	BEXTR,
	SHLX, SARX, SHRX,

	PERMQ, PERMPD, 
	PBLENDD, BLENDPS, BLENDPD, PBLENDW,
	PERM2F128, PERM2I128,
	ROUNDPS, ROUNDPD, ROUNDSS, ROUNDSD, 
	PALIGNR, 
	PEXTRB, PEXTRD, 
	INSERTPS, EXTRACTPS,
	INSERTF128, EXTRACTF128,
	INSERTI128, EXTRACTI128,
	CVTPS2PH, 
	PINSRB, PINSRD, 
	DPPS, DPPD,
	MPSADBW,
	PCLMULQDQ,
	PCMPESTRM, PCMPESTRI, PCMPISTRM, PCMPISTRI,
	SHA1RNDS4,
	AESKEYGEN, 
	RORX,

	PREFETCHNTA, PREFETCHT0, PREFETCHT1, PREFETCHT2,

	SLDT, STR, LLDT, LTR, VERR, VERW,
	SGDT, SIDT, LGDT, LIDT, SMSW, LMSW, INVLPG,
	SWAPGS, RDTSCP,
	CMPXCH8B, CMPXCHG16B,
	VMPTRLD, VMPTRST,
	VMCLEAR, VMXON,
	BLSR, BLSMSK, BLSI,

	VPTERNLOGD,
	VINSERTI32X8, VINSERTI64X4,
	VSHUFI32X4, VSHUFI64X2,
	VZEROUPPER, VZEROALL,

	EXTENDED_OPCODE
};

#ifdef __cplusplus
extern "C"
{
#endif

	extern const char* mnemonicStrs[];

#ifdef __cplusplus
}
#endif

unsigned char isOpcodeMov(enum Mnemonic opcode);

unsigned char isOpcodeAdd(enum Mnemonic opcode);

unsigned char isOpcodeSub(enum Mnemonic opcode);

unsigned char isOpcodeAnd(enum Mnemonic opcode);

unsigned char isOpcodeOr(enum Mnemonic opcode);

unsigned char isOpcodeXor(enum Mnemonic opcode);

unsigned char isOpcodeShl(enum Mnemonic opcode);

unsigned char isOpcodeShr(enum Mnemonic opcode);

unsigned char isOpcodeMul(enum Mnemonic opcode);

unsigned char isOpcodeDiv(enum Mnemonic opcode);

unsigned char isOpcodeCvtToDbl(enum Mnemonic opcode);

unsigned char isOpcodeCvtToFlt(enum Mnemonic opcode);

unsigned char isOpcodeCall(enum Mnemonic opcode);

unsigned char isOpcodeReturn(enum Mnemonic opcode);

unsigned char isOpcodeJcc(enum Mnemonic opcode);

unsigned char isOpcodeCMOVcc(enum Mnemonic opcode);
