#pragma once
#include "registers.h"

// Intel 64 and IA-32 Architectures Software Developer’s Manuals:
//	intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html

// underscore prefixes are to avoid name conflicts

enum Mnemonic
{
	NO_MNEMONIC,

	MOVUPS, MOVUPD, MOVSS, MOVSD, MOVSX, MOVD, MOVAPS, MOVAPD, MOVLPS, MOVLPD, MOVSLDUP, MOVDDUP, MOVHPS, MOVHPD, MOVSHDUP, MOVNTPS, MOVNTPD, MOVMSKPS, MOVMSKPD, MOVS, MOVSXD, MOVZX, MOVQ, MOVDQA, MOVDQU, MOVNTI, MOVQ2DQ, MOVDQ2Q, PMOVMSKB, MOVNTQ, MOVNTDQ, MASKMOVQ, MASKMOVDQU, MOV,
	LEA, 
	ADDPS, ADDPD, ADDSS, ADDSD, HADDPD, HADDPS, XADD, PADDQ, ADD,
	SUB, AND, OR, XOR, SHL, SHR, SHLD, SHRD,
	
	CVTPS2PD, CVTPD2PS, CVTSS2SD, CVTSD2SS, CVTPI2PS, CVTPI2PD, CVTSI2SS, CVTSI2SD, CVTTPS2PI, CVTTPD2PI, CVTTSS2SI, CVTTSD2SI, CVTPS2PI, CVTPD2PI, CVTSS2SI, CVTSD2SI, CVTDQ2PS, CVTPS2DQ, CVTTPS2DQ, CVTTPD2DQ, CVTDQ2PD, CVTPD2DQ,
	COMISS, COMISD,

	IMUL, IDIV,

	MULPS, MULPD, MULSS, MULSD,
	PMULLW,

	CMOVO, CMOVNO, CMOVB, CMOVNB, CMOVZ, CMOVNZ, CMOVBE, CMOVA, CMOVS, CMOVNS, CMOVP, CMOVNP, CMOVL, CMOVGE, CMOVLE, CMOVG,
	
	SQRTPS, SQRTPD, SQRTSS, SQRTSD, RSQRTPS, RSQRTSS,

	ANDPS, ANDPD, ANDNPS, ANDNPD, PAND, PANDN,
	ORPS, ORPD, XORPD, XORPS,
	SUBPS, SUBPD, SUBSS, SUBSD, HSUBPD, HSUBPS,
	MINPS, MINPD, MINSS, MINSD,
	DIVPS, DIVPD, DIVSS, DIVSD,
	MAXPS, MAXPD, MAXSS, MAXSD,

	ADDSUBPD, ADDSUBPS,

	PUNPCKLBW, PUNPCKLWD, PUNPCKLDQ, PACKSSWB, PACKUSWB, PUNPCKHBW, PUNPCKHWD, PUNPCKHDQ, PACKSSDW, PUNPCKLQDQ, PUNPCKHQDQ,
	PCMPGTB, PCMPGTW, PCMPGTD,

	PSHUFW, PSHUFD, PSHUFHW, PSHUFLW,

	PCMPEQB, PCMPEQW, PCMPEQD,

	CMPPS, CMPPD, CMPSS, CMPSD,

	SHUFPS, SHUFPD,

	PSRLW, PSRLD, PSRLQ,

	PSUBUSB, PSUBUSW,
	PMINUB, 
	PADDUSB, PADDUSW,
	PMAXUB,
	PAVGB, PSRAW, PSRAD, PAVGW, PMULHUW, PMULHW,
	PSUBSB, PSUBSW, PMINSW, POR, PADDSB, PADDSW, PMAXSW, PXOR,
	PSLLW, PSLLD, PSLLQ, PMULUDQ, PMADDWD, PSADBW, 
	PSUBB, PSUBW, PSUBD, PSUBQ, PADDB, PADDW, PADDD,

	FXSAVE, FXRSTOR, LDMXCSR, STMXCSR, XSAVE, XRSTOR, XSAVEOPT, CLFLUSH,
	LFENCE, MFENCE, SFENCE,
	RDFSBASE, RDGSBASE, WRFSBASE, WRGSBASE,
	RDRAND, RDSEED, RDPID,

	AAA, AAD, AAM, AAS, ADC, ARPL,
	BOUND, BSF, BSR, BSWAP, BT, BTC, BTR, BTS, BNDLDX, BNDMOV, BNDCL, BNDCU, BNDSTX, BNDMK, BNDCN,
	CALL_FAR, CALL_NEAR, CDQ, CLAC, CLC, CLD, CLI, CLTS, CMC, CMP, CMPS, CMPXCHG, CPUID, CBW, CWDE, CDQE,
	DAA, DAS, DEC, DIV,
	EMMS, ENCLS, ENCLU, ENDBR, ENTER,
	F2XM1, FABS, FADD, FADDP, FBLD, FBSTP, FCHS, FCLEX, FCMOVB, FCMOVBE, FCMOVE, FCMOVNB, FCMOVNBE, FCMOVNE, FCMOVNU, FCMOVU, FCOM, FCOMI, FCOMIP, FCOMP, FCOMPP, FCOS, FDECSTP, FDIV, FDIVP, FDIVR, FDIVRP, FFREE, FIADD, FICOM, FICOMP, FIDIV, FIDIVR, FILD, FIMUL, FINCSTP, FINIT, FIST, FISTP, FISTTP, FISUB, FISUBR, FLD, FLD1, FLDCW, FLDENV, FLDL2E, FLDL2T, FLDLG2, FLDLN2, FLDPI, FLDZ, FMUL, FMULP, FNOP, FPATAN, FPREM, FPREM1, FPTAN, FRNDINT, FRSTOR, FSAVE, FSCALE, FSIN, FSINCOS, FSQRT, FST, FSTCW, FSTENV, FSTP, FSTSW, FSUB, FSUBP, FSUBR, FSUBRP, FTST, FUCOM, FUCOMI, FUCOMIP, FUCOMP, FUCOMPP, FXAM, FXCH, FXTRACT, FYL2X, FYL2XP1, 
	GETSEC,
	HLT,
	_IN, INC, INS, _INT, INT1, INT3, INTO, INVD, IRET,
	JA_SHORT, JB_SHORT, JBE_SHORT, JG_SHORT, JL_SHORT, JLE_SHORT, JNB_SHORT, JGE_SHORT, JNO_SHORT, JNP_SHORT, JNS_SHORT, JNZ_SHORT, JO_SHORT, JP_SHORT, JS_SHORT, JZ_SHORT, JMP_SHORT, JMP_FAR, JMP_NEAR, JRCXZ, JMPE,
	LAHF, LAR, LDDQU, LDS, LEAVE, LES, LFS, LGS, LODS, LOOP, LOOPNZ, LOOPZ, LSL, LSS, LZCNT,
	MONITOR, MUL, MWAIT,
	NEG, NOP, NOT,
	_OUT, OUTS,
	POP, POPAD, POP_DS, POP_ES, POP_FS, POP_GS, POP_SS, POPF, PREFETCHW, PUSH, PUSHAD, PUSH_CS, PUSH_DS, PUSH_ES, PUSH_FS, PUSH_GS, PUSH_SS, PUSHF, POPCNT, PINSRW, PEXTRW,
	RCL, RCR, RDMSR, RDPMC, RDTSC, RET_FAR, RET_NEAR, ROL, ROR, RSM, RCPPS, RCPSS,
	SAHF, SAR, SBB, SCAS, SETA, SETB, SETBE, SETG, SETL, SETLE, SETNB, SETNL, SETNO, SETNP, SETNS, SETNZ, SETO, SETP, SETS, SETZ, STAC, STC, STD, STI, STOS, SYSCALL, SYSENTER, SYSEXIT, SYSRET,
	TEST, TZCNT,
	UCOMISD, UCOMISS, UNPCKHPD, UNPCKHPS, UNPCKLPD, UNPCKLPS,
	VMCALL, VMFUNC, VMLAUNCH, VMRESUME, VMXOFF, VMREAD, VMWRITE,
	WAIT, WBINVD, WRMSR,
	XABORT, XBEGIN, XCHG, XEND, XGETBV, XLAT, XSETBV, XTEST,

	EXTENDED_OPCODE
};

// Appendix A: A.2
// "Operands are identified by a two-character code of the form Zz. The first character, an uppercase letter, specifies
//	the addressing method; the second character, a lowercase letter, specifies the type of operand."
enum OperandCode
{
	ONE,
	AL_CODE, CL_CODE, AX_CODE, DX_CODE,
	rAX, rCX, rDX, rBX, rSP, rBP, rSI, rDI,
	rAX_r8, rCX_r9, rDX_r10, rBX_r11, rSP_r12, rBP_r13, rSI_r14, rDI_r15,
	AL_R8B, CL_R9B, DL_R10B, BL_R11B, AH_R12B, CH_R13B, DH_R14B, BH_R15B,
	ST0_CODE, ST1_CODE, ST2_CODE, ST3_CODE, ST4_CODE, ST5_CODE, ST6_CODE, ST7_CODE,
	Eb, Ev, Ew, Ep, Ey,
	Gb, Gd, Gv, Gz, Gw, Gy,
	M, Mw, Md, Mp, Ma, Mq, Mt, Mps, Mpd, My, Mx,
	Ib, Iv, Iz, Iw,
	Yb, Yv, Yz,
	Xb, Xv, Xz,
	Jb, Jz,
	Nq,
	Ob, Ov,
	Rd, Ry, Rv,
	Cd,
	Dd,
	Sw,
	Ap,
	Pd, Ppi, Pq,
	Qd, Qpi, Qq,
	Ups, Upd, Udq, Uq, Ux,
	Vps, Vpd, Vx, Vss, Vsd, Vdq, Vy, Vq,
	Wps, Wpd, Wss, Wsd, Wdq, Wx, Wq,
	Hps, Hpd, Hx, Hss, Hsd, Hdq, Hq,
	
	A_BYTE, // added for the F3 0F 1E FA (ENDBR) instruction. IDK what FA is supposed to be so leaving this here
	NO_OPERAND_CODE
};

enum OpcodeSuperscript
{
	i64,  // invalid in 64-bit mode
	o64,  // only available in 64-bit mode
	d64,  // operand size defaults to 64-bit size
	f64,  // operand size forced to 64-bit size
	f256, // operand size forced to 256-bit size

	NO_SUPERSCRIPT
};

struct Opcode
{
	enum Mnemonic mnemonic;
	char extensionGroup; // -1 if the opcode is not an extended one. 0 = Group 1; 1 = Group 1A; from there this number corresponds to the actual group number
	enum OperandCode operands[4];
	enum OpcodeSuperscript opcodeSuperscript;
};

#ifdef __cplusplus
extern "C"
{
#endif

	extern const char* mnemonicStrs[];

#ifdef __cplusplus
}
#endif

unsigned char isOpcodeCall(enum Mnemonic opcode);
